name: esp32c3_2M_Sc_Mqtt

on: 
  workflow_dispatch:

jobs:
  build_idf44:
    runs-on: ubuntu-20.04
    
    steps:
    - name: git clone micropython
      run: |
        mkdir -p ~/esp
        cd ~/esp
        git clone -b esp32c3 https://github.com/youxinweizhi/micropython.git  
    
    - name: Install packages
      run: |
        cd ~/esp/micropython
        source tools/ci.sh && ci_esp32_idf44_setup
        
    - name: Build
      run: |
        source ~/esp/micropython/esp-idf/export.sh
        cd ~/esp/micropython
        make  -C mpy-cross
        make  -C ports/esp32 submodules
        make  -C ports/esp32 BOARD=MYESP32_C3_2M

    - name: Upload firmware
      uses: actions/upload-artifact@main
      with:
        name: esp32c3_2M_smartconfig_mqtt_firmware
        path: ~/esp/micropython/ports/esp32/build*/firmware.bin