name: esp32c3_4M_Espnow_Sc_Mqtt_St7789

on: 
  push:
  workflow_dispatch:

jobs:
  build_idf44:
    runs-on: ubuntu-20.04
    
    steps:    
    - name: git clone micropython
      run: |
        mkdir -p ~/esp
        cd ~/esp
        git clone -b espnow-g20-v1.18 https://github.com/glenn20/micropython.git
    
    - name: clone st7789
      run: |
        git clone https://github.com/russhughes/st7789_mpy.git

    - name: clone this project
      run: |
        git clone https://github.com/youxinweizhi/actions.git
        cp -rf actions/micropython/main ~/esp/micropython/ports/esp32/
        cp -rf actions/micropython/MYESP32_C3_4M ~/esp/micropython/ports/esp32/boards/
        cp -rf actions/micropython/help.c ~/esp/micropython/ports/esp32/help.c
        cp -rf actions/micropython/smartconfig.c ~/esp/micropython/ports/esp32/smartconfig.c       
    
    - name: Install packages
      run: |
        cd ~/esp/micropython
        source tools/ci.sh && ci_esp32_idf44_setup
        
    - name: Build
      run: |
        source ~/esp/micropython/esp-idf/export.sh
        cd ~/esp/micropython
        make  -C mpy-cross
        make  -C ports/esp32 submodules
        make  -C ports/esp32 BOARD=MYESP32_C3_4M USER_C_MODULES=../../../../st7789_mpy/st7789/micropython.cmake 

    - name: Upload firmware
      uses: actions/upload-artifact@main
      with:
        name: esp32c3_4M_espnow_smartconfig_mqtt_ping_st7789_firmware
        path: ~/esp/micropython/ports/esp32/build*/firmware.bin