name: esp32c3

on:
  push:
    tags:
        - v*

jobs:
  build_idf44:
    runs-on: ubuntu-20.04
    steps:
    - name: git clone micropython
      run: |
        mkdir -p ~/esp
        cd ~/esp
        git clone https://github.com/micropython/micropython.git
        
    - name: Install packages
      run: |
        cd ~/esp/micropython
        source tools/ci.sh && ci_esp32_idf44_setup
    - name: Build
      run: |
        cd ~/esp/micropython
        source tools/ci.sh && ci_esp32_build
